version: '3.8'

services:

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      # NOTE: development-only option
      - ALLOW_PLAINTEXT_LISTENER=yes
      # NOTE: development-only option
    ports:
      - 9092:9092
